
spring:
  datasource:
    url: jdbc:mysql://junction.proxy.rlwy.net:15194/railway
    username: root
    password: yVQaoLKVfONVqXqrJsWfDeRfVaarlmbu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
